config/urls.py
from django.contrib import admin
from django.urls import path
from products import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    path("baskets/", include("baskets.urls")),
    path("users/", include("users.urls")),
    path("lists/", include("lists.urls")),
    path("conversations/", include("conversations.urls"))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kkma_chatbot-main/chatbot_test-main/restfulapiserver/urls.py
from django.urls import re_path as url
from django.urls import include
from addresses import views
from django.urls import path
from django.contrib import admin
from django.urls import re_path

urlpatterns = [
    path('addresses/', views.address_list),
    path('addresses/<int:pk>/', views.address),
    path('login/', views.login),
    path('app_login/', views.app_login),
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat_service/', views.chat_service),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:product_pk>", views.toggle_room, name="toggle_room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),]

products/urls.py
from django.urls import path
from . import views
from products import views as products_view
from django.conf import settings
from django.conf.urls.static import static

app_name = "product"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("products", products_view.all_products, name="product_list"),
    path("search/", products_view.search, name="search"),
    path("products/<int:pk>", views.ProductDetail.as_view(), name="detail"),
    path("products/create", views.CreateProductView.as_view(), name="create"),
    path("<int:pk>/edit", views.EditProjectView.as_view(), name="edit"),
    path('<int:pk>/delete', views.DeleteProductView.as_view(), name='delete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = "user"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("email_verify/", views.email_verify, name="verify"),
    path("verify/<str:key>", views.complete_verification,
         name="complete-verification"),
    # 비밀번호 초기화
    path('password_reset/', views.MyPasswordResetView.as_view(),
         name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path("password_verify/", views.password_verify, name="password-verify"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>

templates/partials/nav.html
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
</head>
{% load static %}
<header class="header">
  <div class="header__logo">
    <i class="fa-solid fa-moon fa-2x" style="color: yellow"></i>
    <h1 class="header__logo__title">
      <a href="{% url 'product:home' %}">Daljak</a>
    </h1>
  </div>
  <nav class="header__nav">
    <ul class="header__menu">
      <li>
        <a class="header__menu__item active" href="{% url 'product:home' %}"
          >Home</a
        >
      </li>

      <li>
        <a class="header__menu__item" href="{% url 'product:product_list' %}"
          >Products</a
        >
      </li>

      {% if user.is_authenticated %}
      <li>
        <a class="header__menu__item" href="{% url 'lists:see-favs' %}"
          >Favs
        </a>
      </li>
      {% endif %} {% if user.is_authenticated %}
      <li>
        <a class="header__menu__item" href="{% url 'product:create' %}"
          ><i class="fas fa-pencil-alt" style="color: white"></i
        ></a>
      </li>
      {% endif %} {% if user.is_authenticated %}
      <li>
        <a class="header__menu__item" href="{% url 'user:logout' %}">Logout </a>
      </li>

      <!-- <li>
        <a href="{{user.get_absolute_url}}">Profile</a>
      </li> -->

      {% else %}
      <li>
        <a class="header__menu__item" href="{% url 'user:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
    <button class="header__toggle" aria-label="navigation menu toggle">
      <i class="fa-solid fa-bars"></i>
    </button>
  </nav>
  <script
    type="text/javascript"
    src="{% static 'js/active_menu.js' %}"
  ></script>
</header>

templates/partials/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
   <script
      src="https://kit.fontawesome.com/132c10257e.js"
      crossorigin="anonymous"
    ></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </head>
  <body>
    {% extends "base.html" %} {% block content%} {% load static %}
    <div class="modal hidden">
          <button id="close-btn"><ion-icon class="icon" size="large" name="close-outline"></ion-icon></button>
          <form method="GET" action="{% url 'product:search' %}">
            
          <div class="modal__content">
                <h1>형태</h1>
             <div class="modal__filter">
            
            <ul class="modal__list">
                {% for pot in shape %}
                    <li>
                       <input id="a_{{abc.pk}}" name="shape" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in shapes_s %}
                            checked
                        {% endif %} />
                        <label for="a_{{abc.pk}}">{{pot.name}}</label>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <h1>관념별</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in mind %}
                    <li>
                        <input id="a_{{pot.pk}}" name="mind" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in mind_s %}
                            checked
                        {% endif %} 
                        
                         />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                    </li>
                {% endfor %}
            </ul>
        </div>

         <h1>색깔</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in color %}
                    <li>
                              <input id="a_{{pot.pk}}" name="color" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in color_s %}
                            checked
                        {% endif %} />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                
                    </li>
                {% endfor %}
            </ul>
        </div>
         <h1>기타</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in other %}
                    <li>
                       <input id="a_{{pot.pk}}" name="other" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in other_s %}
                            checked
                        {% endif %}  />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                       
                    </li>
                {% endfor %}
            </ul>  
        </div>

        <div class="modal-button">
          <p class="modal-button__x">전체해제</p>
          <button class="modal-button__content">조회</button>
        </div>
         
          </div>
          </form>
        </div>
      <div class="home">
        <div class="pic-filter">
            <ul>
        
      </ul>
 
        
         

           <button class="pic-filter__filterbtn">   
              <i class="fas fa-bars">필터</i></button>
        </div>


      <div class="pic-list__list">
        {% for abcd in abc %}
        <div>
        <a href="" class="project" target="blank" data-type="new">
          
          
           
          <img src="{{abcd.get_photo_url}}" class="project__img" />
          <div class="project__description">
            <h3>{{abcd.title}}</h3>
            <span>{{abcd.content}}</span>
          </div>
         
        </a>  
        <div class="project__text">
            <h3>{{abcd.title}}</h3>
            <span>{{abcd.content}}</span>
          </div>
        </div>
        {% endfor %}
      </div>


      <div class="pic-list__page">
        {% if potato.has_previous %}
        <a class="pic-list__pageicons" href="?page={{potato.number|add:-1}}"><i class="fas fa-chevron-left  "></i></a>
       {% endif %}

         Page {{potato.number}} of {{potato.paginator.num_pages}}
          
       {% if potato.has_next  %}
      
        <a class="pic-list__pageicon" href="?page={{potato.number|add:1}}"> <i class="fas fa-chevron-right "></i></a>
       {% endif %}


        </div>


      <div>
          <form method="get" action="{% url 'product:search' %}"  class="picture__search">
         
            <div class="pic__search-box">
                <input name="city" placeholder="" class="pic__search-bar " value="{{city}}" onchange="onSubmit()">
                <div class="pic__search-placeholder">
                  <i class="fas fa-search"></i></input>
                  <p class="sc-searchbox-placeholder-text">Search </p>
                </div>
                
            </div>
            <!-- 글 작성 버튼은 관리자만 보이도록 해주세요 -->
          
        </form>
      </div>


  

    
      <!-- Arrow up -->
      <aside>
        <a class="arrow-up" href="#home" title="back to top">
          <i class="fab fa-facebook-messenger"></i>
        </a>
      </aside>


      <footer id="contact" class="section">
      <div class="max-container">
        <h2 class="title">Let&#39;s talk</h2>
        <p class="description">donghe1472@gmail.com</p>
        <ul class="contact__links">
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my github link"
            >
              <i class="fa-brands fa-github"></i>
            </a>
          </li>
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my linkedin link"
            >
              <i class="fa-brands fa-linkedin"></i>
            </a>
          </li>
        </ul>
        <p>ⓒ원광대학교 컴퓨터소프트웨어공학과</p>
      </div>
    </footer>


     <script type="text/javascript" src="{% static 'js/arrow-sec.js' %}"></script>
   
   
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/pic-filter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modal.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
     <script type="text/javascript" src="{% static 'js/pic-fav.js' %}"></script>
    <script>  
      const input = document.querySelector(".pic__search-bar");
      function onSubmit() {
        console.log(input.value);
      if(!input.value) {
        input.style.marginLeft = "10%";
      }

      else{
        console.log("dlskwl");
        input.classList.add("active");
      }
}

    </script>
    {% endblock content %}

</html>