chatbot/urls.py
from django.urls import path
from . import views

app_name = "chatbot"
urlpatterns = [
    # path('addresses/', views.address_list),
    # path('addresses/<int:pk>/', views.address),
    # path('login/', views.login),
    # path('app_login/', views.app_login),
    # path('admin/', admin.site.urls),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.chat_service, name="chat"),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from products import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    path("baskets/", include("baskets.urls")),
    path("users/", include("users.urls")),
    path("lists/", include("lists.urls")),
    path("conversations/", include("conversations.urls"))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

kkma_chatbot-main/chatbot_test-main/restfulapiserver/urls.py
from django.urls import re_path as url
from django.urls import include
from addresses import views
from django.urls import path
from django.contrib import admin
from django.urls import re_path

urlpatterns = [
    path('addresses/', views.address_list),
    path('addresses/<int:pk>/', views.address),
    path('login/', views.login),
    path('app_login/', views.app_login),
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat_service/', views.chat_service),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:product_pk>", views.toggle_room, name="toggle_room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),]

products/urls.py
from django.urls import path
from . import views
from products import views as products_view
from django.conf import settings
from django.conf.urls.static import static

app_name = "product"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("products", products_view.all_products, name="product_list"),
    path("search/", products_view.search, name="search"),
    path("products/<int:pk>", views.ProductDetail.as_view(), name="detail"),
    path("products/create", views.CreateProductView.as_view(), name="create"),
    path("<int:pk>/edit", views.EditProjectView.as_view(), name="edit"),
    path('<int:pk>/delete', views.DeleteProductView.as_view(), name='delete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from common.models import Common
from common import models as core_models


class AbstractItem(core_models.Common):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Department(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "학과"


class Species(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "종류"


class Grade(AbstractItem):

    """ Facility Model Definition """

    pass

    class Meta:
        verbose_name_plural = "학년"


class Repair(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "보수"


class TeamNumber(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "팀원수"


class Category(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "카테고리"


class SearchHistory(models.Model):

    query = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="ss",  null=True, blank=False
    )
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.query


class Product(Common):

    SEMI_A = "it"
    SEMI_B = "마케팅"
    SEMI_C = "언어"
    SEMI_D = "제작/글쓰기"

    SEMI_CHOICES = (
        (SEMI_A, "it"),
        (SEMI_B, "마케팅"),
        (SEMI_C, "언어"),
        (SEMI_D, "제작/글쓰기"),
    )
    registrant = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        null=True
    )
    filter = models.CharField(
        choices=SEMI_CHOICES, default='', max_length=10, blank=False, null=True)
    title = models.CharField(max_length=50, null=True,)
    content = models.TextField(
        null=True,
    )
    explanation = models.TextField(
        null=True,
        blank=True,
    )
    profile = models.ImageField(blank=True)
    image = models.ManyToManyField(
        # 이미지를 이미지필드로 할것이냐 manytomany로할것이냐=> 이미지 필드는 여개 선택인 안됨
        # => m:m으로 하자
        "photos.Photo",
        blank=True,
    )
    categories = models.ForeignKey(   # 카테고리
        "product_categories.ProductCategory",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    # 필터

    department = models.ManyToManyField(
        "Department", related_name="department", blank=True)
    species = models.ManyToManyField(
        "Species", related_name="species", blank=True)
    grade = models.ManyToManyField("Grade", blank=True)
    repair = models.ManyToManyField("Repair", blank=True)

    team_number = models.ManyToManyField(
        "TeamNumber", related_name="team", blank=True)
    meet = models.BooleanField(default=True, blank=True)
    category = models.ManyToManyField(
        "Category", related_name="categoy", blank=True)
    framework = models.CharField("FrameWork", max_length=50, blank=True)

    @property
    def get_photo_url(self):
        if self.profile:
            return self.profile.url
        else:
            return "/static/images/user.jpg"

    def __str__(self):
        return f"{self.title} / by {self.registrant}"

products/forms.py
from django import forms
from . import models


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = (
            "title",
            "profile",
            "content",
            "explanation",
            "department",
            "species",
            "grade",
            "repair",
            "team_number",
            "meet",
            "category",
            "framework"
        )
      
        widgets = {
            "title": forms.TextInput(attrs={'placeholder': '프로젝트 이름'}),
            "content": forms.TextInput(attrs={'placeholder': '간단한 설명을 적어주세요'}),
            "thumnail_img": forms.FileInput(attrs={'placeholder': '사용할 이미지를 넣어주세요'}),
            "explanattion": forms.TextInput(attrs={'placeholder': "필요한 설명을 적어주세요"})
            # forms.NumberInput을 사용
        }

        lables = {

        }   

    def save(self, *args, **kwargs):
        project = super().save(commit=False)
        repair = self.cleaned_data.get("repair")
        project.repair = repair
        project.save()
        
        return project

products/views.py
from rest_framework.decorators import api_view
from rest_framework.exceptions import NotFound
from rest_framework.response import Response
from rest_framework.status import HTTP_204_NO_CONTENT
from rest_framework.views import APIView
from django.core.paginator import Paginator
from .serializers import ProductSerializer
from django.views.generic import ListView, DetailView
from . import models
from datetime import datetime
from django.shortcuts import render, redirect
from users import mixins as user_mixins
from . import models, forms
from django.views.generic import ListView, DetailView, View, UpdateView, FormView, DeleteView
from django.shortcuts import render, redirect, reverse


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Product
    paginate_by = 10
    paginate_orphans = 5
    context_object_name = "rooms"


def all_products(request):
    page = request.GET.get("page")
    all_product = models.Product.objects.all()
    paginator = Paginator(all_product, 10)
    products = paginator.get_page(page)

    shapes_s = models.Species.objects.all()
    mind_s = models.Department.objects.all()
    color_s = models.Grade.objects.all()
    other_s = models.Repair.objects.all()

    return render(request, "products/products.html", context={"potato": products,  "mind": mind_s, "color": color_s, "other": other_s, "shape": shapes_s, })


def search(request):
    city = request.GET.get("city")

    shapes_s = models.Department.objects.all()
    mind_s = models.Species.objects.all()
    color_s = models.Grade.objects.all()
    other_s = models.Repair.objects.all()

    shapes = request.GET.getlist("shape")
    colors = request.GET.getlist("color")
    minds = request.GET.getlist("mind")
    others = request.GET.getlist("other")

    filter_args = {}

    if len(shapes) > 0:
        for s_amenity in shapes:
            filter_args["department__pk"] = int(s_amenity)

    if len(colors) > 0:
        for s in colors:
            filter_args["species__id"] = int(s)

    if len(minds) > 0:
        for abc in minds:
            filter_args["grade__id"] = int(abc)

    if len(others) > 0:
        for oo in others:
            filter_args["repair__id"] = int(oo)

    if 'city' in request.GET:
        filter_args["title__contains"] = city
    picture = models.Product.objects.all().filter(**filter_args)

    # search_history = None
    # if city:
    #     search_his
    #
    #
    #
    # tory = models.SearchHistory(query=city, user=request.user)
    #     search_history.save()

    # if city and request.user.is_authenticated:
    #     search_history_list = models.SearchHistory.objects.filter(
    #         query=city, user=request.user)
    #     if search_history_list.exists():  # 조건에 맞는 객체가 존재하는지 확인
    #         search_history = search_history_list.first()  # 첫 번째 객체 선택
    #         search_history.count += 1
    #         search_history.save()
    #     else:
    #         # 새로운 검색어라면 객체를 생성하여 저장
    #         search_history = models.SearchHistory(
    #             query=city, user=request.user, count=1)
    #         search_history.save()

    # search_history_list = models.SearchHistory.objects.order_by(
    #     '-timestamp')[:8]

    query = request.GET.get("query")

    return render(request, "partials/search.html", {"abc": picture, "mind": mind_s, "color": color_s, "other": other_s, "shape": shapes_s, "city": city, 'query': query})


class ProductDetail(DetailView):
    model = models.Product
    context_object_name = "product"


class CreateProductView(user_mixins.LoggedInOnlyView, FormView):

    form_class = forms.CreateProductForm
    template_name = "products/product_create.html"

    def form_valid(self, form):
        project = form.save()
        project.registrant = self.request.user
        project.save()
        # project.success(self.request, "Photo Uploaded")
        return redirect(reverse("product:product_list"))


class EditProjectView(UpdateView):

    model = models.Product
    template_name = "products/product_edit.html"
    fields = (
        "title",
        "content",
        "profile",
        "department",
        "species",
        "grade",
        "repair",
    )

    def get_success_url(self):
        return reverse("product:product_list")


class DeleteProductView(DeleteView):

    model = models.Product
    template_name = "products/product_delete.html"

    def get_success_url(self):
        return reverse("product:product_list")

templates/products/product_create.html
<head>
    <link rel="stylesheet" href="../../static/css/components/status-bar.css" />
    <link rel="stylesheet" href="../../static/css/components/create-page.css" />
    <link rel="stylesheet" href="../../static/css/components/button.css" />
</head>

<body class="create-page">
     {% extends "base.html" %} {% block content%}  
  {% load static %}
    <main id="create-main">
        <div class="create__title">💻 제품 작성</div>
        <form method="POST" class="create" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="create-wrap_second">
    {% for field in form %} 
    
    <labelc class="create__content-label" for="create__cont-title">
      <div class="create__content-label-wrap">
    {{field.label}} {{field}}
      </div>
    </label> 


 {% endfor %}
  <div class="btn_wrap">
  <div class="btn-component create-btn">
    <button>create</button>
  </div>
</div>
</form>

        </div>
    </main>

     <!-- Arrow up -->
      <aside>
        <a href="{% url 'chatbot:chat'%}" class="arrow-up"  title="back to top">
          <i class="fab fa-facebook-messenger"></i>
        </a>
      </aside>


      <footer id="contact" class="section">
      <div class="max-container">
        <h2 class="title">Let&#39;s talk</h2>
        <p>ⓒ원광대학교 컴퓨터소프트웨어공학과</p>
        <p class="description">주소 : 전라북도 익산시 익산대로 460(원광대학교) </p>
        <ul class="contact__links">
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my github link"
            >
              <i class="fa-brands fa-github"></i>
            </a>
          </li>
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my linkedin link"
            >
              <i class="fa-brands fa-linkedin"></i>
            </a>
          </li>
        </ul>
        <p class="description">donghe1472@gmail.com</p>
        <p class="description">si990819@gmail.com</p>
        <p class="description">hanse7260@gmail.com</p>

        <p class="description">moveg001115@gmail.com</p>
      </div>
    </footer>
       {% endblock content %}
</body>

templates/products/product_detail.html
{% extends "base.html" %} {% load on_favs i18n %} {% block content%} {% load static %}

<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
<div class="container mx-auto columns-1 justify-around pb-56 mr-96">
  <img src="{{product.get_photo_url}}" class="project__img" />
  <div class=>
    <div class="flex justify-between mb-8">
      <div class="mb-5">
        
        <div>
        <span class="text-6xl font-medium ">{{product.title}}</span>
        <span class="text-gray-700 font-medium text-2xl">{{product.content}}</span>
        </div>
        <div class="flex">
          <i class="mb-10 fa-solid fa-message fa-2x mr-2" id="messageIcon" href=""><span> </span></i>
            <div class="text-gray-700 font-medium text-2xl mt ">{{product.registrant}}</div>
         
        </div>
      
      </div>
      <div class="mt-24 flex " id="hello">
        <p class=" far fa-star fa-3x topHeart mr-1" style="color: black;" ></p>
         <p class=" fa-solid fa-star fa-3x bottomHeart mr-1" style="color: yellow; display: none;" ></p>
         <i class="far fa-edit fa-3x " id="editIcon"></i>
         <i class="far fa-trash-alt fa-3x mr-1" id="deleteIcon"></i>
        
     </div>
     
    </div>
    <div class="messages">
    
     </div>
    <div class="flex flex-wrap flex-col columns-1">
     <div class="mb-5">
      <span class="mb-5 ">
       
        {% for department in product.department.all %} <i class="fa-solid fa-gear mr-3"></i>{{ department.name }}
      </span>
      {% endfor %}
      <span class="mb-5 "
        > {% for abc in product.species.all %} <i class="fa-solid fa-square-check mr-3"></i> {{ abc.name }}
      </span>
      {% endfor %}
      <span class="mb-5 "
        >{% for abc in product.grade.all %}  <i class="fas fa-fingerprint mr-3"></i> {{ abc.name }}
      </span>
      {% endfor %}
      <span class="mb-5"
        >{% for abc in product.repair.all %} <i class="fas fa-tag mr-3"></i> {{ abc.name }}
      </span>
      {% endfor %}

      </div>
    </div>
    <p class="border-b border-gray-400 pb-8 ">{{room.description}}</p>
    <div class="border-b border-gray-400 pb-8 mt-8">
      <h4 class="font-medium text-lg mb-5">이 사용자가 올린 데이터</h4>
      <div class="flex">
      {% for a in user.product_set.all %}
          <div class="detail__content">
          <img src="{{a.get_photo_url}}" class="project__image w-3 h-3" />
          <div class=>
            <h3 class="text-3xl">{{a.title}}</h3>
            <span>{{a.content}}</span>
          </div>
         </div>
      
      {% endfor %}
      </div>
    </div>
    <div class="border-b border-gray-400 pb-8 mt-8 mb-8">
      <h4 class="font-medium text-lg mb-5">기술수준</h4>
     <span class="mb-5  ">
        {% for department in product.team_number.all %} <div class="notice__tags">
                <div class="notice__tag">
                    <div>{{department}}</div>
                </div>
            </div>
      </span>
      {% endfor %}
      <span class="mb-8 "
        >  
        {% if product.meet %}
        <div class="notice__tag">
                    <div>만남o</div>
                </div>
 {% else %}
                <div class="notice__tag">
                    <div>만남x</div>
                </div>
                {% endif %}
      </span>
     
      <span class="mb-5 "
        >{% for abc in product.category.all %}  <div class="notice__tag">
                    <div>{{abc}}</div>
                </div>
      {% endfor %}
     
    </div>
  
    <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in product.reviews.all  %}
                        <div class="border-section">
                            <div class="mb-3 ">
                              <div>
                                <i class="fas fa-star text-teal-500" style="color: yellow;"></i>
                        <span class="font-bold text-xl">{{review.rating}}</span>
                              </div>
                                
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{review.writer}}</span>
                                    <span class="text-sm text-gray-500">{{review.created_at|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.content}}</p>
                        </div>
                    {% endfor %}    
                </div>

  </div>
  <div class="w-1/3"></div>

  
</div>

<footer id="contact" class="section">
      <div class="max-container">
        <h2 class="title">Let&#39;s talk</h2>


        <p>ⓒ원광대학교 컴퓨터소프트웨어공학과</p>
        <p class="description">주소 : 전라북도 익산시 익산대로 460(원광대학교) </p>
        <ul class="contact__links">
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my github link"
            >
              <i class="fa-brands fa-github"></i>
            </a>
          </li>
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my linkedin link"
            >
              <i class="fa-brands fa-linkedin"></i>
            </a>
          </li>
        </ul>
        <p class="description">donghe1472@gmail.com</p>
        <p class="description">si990819@gmail.com</p>
        <p class="description">hanse7260@gmail.com</p>

        <p class="description">moveg001115@gmail.com</p>
      </div>
    </footer>
    <script>

      const topHearts = document.querySelectorAll(".topHeart");
const bottomHearts = document.querySelectorAll(".bottomHeart");

topHearts.forEach((topHeart) => {
  topHeart.addEventListener("click", function (e) {
    e.preventDefault();
    topHeart.style.display = "none";
    // 해당 topHeart에 연결된 bottomHeart를 찾아서 보이도록 변경
    const relatedBottomHeart =
      topHeart.parentElement.querySelector(".bottomHeart");
    relatedBottomHeart.style.display = "block";
  });
});

bottomHearts.forEach((bottomHeart) => {
  bottomHeart.addEventListener("click", function (e) {
    e.preventDefault();
    bottomHeart.style.display = "none";
    // 해당 bottomHeart에 연결된 topHeart를 찾아서 보이도록 변경
    const relatedTopHeart =
      bottomHeart.parentElement.querySelector(".topHeart");
    relatedTopHeart.style.display = "block";
  });
});

// 편집 아이콘에 대한 클릭 이벤트 처리
document.getElementById("editIcon").addEventListener("click", function () {
  // 특정 URL로 이동
  window.location.href = "{% url 'product:edit' product.pk %}";
});

// 삭제 아이콘에 대한 클릭 이벤트 처리
document.getElementById("deleteIcon").addEventListener("click", function () {
  // 특정 URL로 이동
  window.location.href = "{% url 'product:delete' product.pk %}";
});

// 삭제 아이콘에 대한 클릭 이벤트 처리
document.getElementById("messageIcon").addEventListener("click", function () {
  // 특정 URL로 이동
  console.log("hello");
  window.location.href = "{% url 'conversations:detail' product.pk %}";
});

document.getElementById("favIcon").addEventListener("click", function () {
  // 특정 URL로 이동
  console.log("hello");
  window.location.href = "{% url 'lists:toggle_room' product.id %}";
});

document.getElementById("favsIcon").addEventListener("click", function () {
  // 특정 URL로 이동
  console.log("hello");
  window.location.href = "{% url 'lists:toggle_room' product.id %}";
});

// DOM이 준비되면 실행될 함수
document.addEventListener("DOMContentLoaded", function () {
  // 첫 번째 아이콘을 선택합니다.
  const favsIcon1 = document.getElementById("favsIcon1");

  // 클릭 이벤트 리스너 등록
  favsIcon1.addEventListener("click", function () {
    // active 클래스를 토글
    if (favsIcon1.classList.contains("active")) {
      favsIcon1.classList.remove("active");
    } else {
      favsIcon1.classList.add("active");
    }
  });
});

     </script>

{% endblock content %}

templates/products/products.html
<!DOCTYPE html>
<html lang="en">
  {% extends "base.html" %} {% block content%}  
  {% load static %}
  <head>
    <link rel="stylesheet" href="{% static 'csss/styles.css' %}" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
     <script
      src="https://kit.fontawesome.com/132c10257e.js"
      crossorigin="anonymous"
    ></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </head>
  <body>
    
    <div class="modal hidden">
          <button id="close-btn"><ion-icon class="icon" size="large" name="close-outline"></ion-icon></button>
          <form method="GET" action="{% url 'product:search' %}">
            
          <div class="modal__content">
                <h1>종류별</h1>
             <div class="modal__filter">
            
            <ul class="modal__list">
                {% for pot in shape %}
                    <li>
                       <input id="a_{{abc.pk}}" name="shape" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in shapes_s %}
                            checked
                        {% endif %} />
                        <label for="a_{{abc.pk}}">{{pot.name}}</label>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <h1>학과별</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in mind %}
                    <li>
                        <input id="a_{{pot.pk}}" name="mind" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in mind_s %}
                            checked
                        {% endif %} 
                        
                         />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                    </li>
                {% endfor %}
            </ul>
        </div>

         <h1>학년별</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in color %}
                    <li>
                              <input id="a_{{pot.pk}}" name="color" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in color_s %}
                            checked
                        {% endif %} />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                
                    </li>
                {% endfor %}
            </ul>
        </div>
         <h1>페이</h1>
             <div class="modal__filter">
            <ul class="modal__list">
                {% for pot in other %}
                    <li>
                       <input id="a_{{pot.pk}}" name="other" type="checkbox" value={{pot.pk}} {% if pot.pk|slugify in other_s %}
                            checked
                        {% endif %}  />
                        <label for="a_{{pot.pk}}">{{pot.name}}</label>
                       
                    </li>
                {% endfor %}
            </ul>  
        </div>

        <div class="modal-button">
          <p class="modal-button__x">전체해제</p>
          <button class="modal-button__content">조회</button>
        </div>
         
          </div>
          </form>
        </div>
      <div class="home" style="display: flex;
    flex-direction: column;">
        <div class="pic-filter">
            <ul>
        {% for item in abc %}
          <li>{{ item }}</li>
       {% endfor %}
      </ul>
 
           <button class="pic-filter__filterbtn">   
              <i class="fas fa-bars">필터</i></button>
        </div>


      <div class="pic-list__list">
        {% for abcd in potato.object_list %}
       
        <div>
        <a href="{% url 'product:detail' pk=abcd.pk %}"  class="project" >
          <img src="{{abcd.get_photo_url}}" class="project__img" />
          <div class="project__description">
            <h3 class="text-3xl">{{abcd.title}}</h3>
            <span>{{abcd.content}}</span>
            
          </div>
         
        </a>  
        <div class="project__text">
            <h3>{{abcd.title}}</h3>
            <span>{{abcd.content}}</span>
            <span>{{abcd.created_at}}</span>
          </div>
        </div>
        {% endfor %}
      </div>


      <div class="pic-list__page">
        {% if potato.has_previous %}
        <a class="pic-list__pageicons" href="?page={{potato.number|add:-1}}"><i class="fas fa-chevron-left  "></i></a>
       {% endif %}

         Page {{potato.number}} of {{potato.paginator.num_pages}}
          
       {% if potato.has_next  %}
      
        <a class="pic-list__pageicon" href="?page={{potato.number|add:1}}"> <i class="fas fa-chevron-right "></i></a>
       {% endif %}


        </div>


      <div>
          <form method="get" action="{% url 'product:search' %}"  class="picture__search">
         
            <div class="pic__search-box">
                <input name="city" placeholder="" class="pic__search-bar " value="{{city}}" onchange="onSubmit()">
                <div class="pic__search-placeholder">
                  <i class="fas fa-search"></i></input>
                  <p class="sc-searchbox-placeholder-text">Search </p>
                </div>
                
            </div>
            <!-- 글 작성 버튼은 관리자만 보이도록 해주세요 -->
          
        </form>
      </div>


  

    
    <!-- Arrow up -->
      <aside>
        <a href="{% url 'chatbot:chat'%}" class="arrow-up"  title="back to top">
          <i class="fab fa-facebook-messenger"></i>
        </a>
      </aside>


      <footer id="contact" class="section">
      <div class="max-container">
        <h2 class="title">Let&#39;s talk</h2>


        <p>ⓒ원광대학교 컴퓨터소프트웨어공학과</p>
        <p class="description">주소 : 전라북도 익산시 익산대로 460(원광대학교) </p>
        <ul class="contact__links">
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my github link"
            >
              <i class="fa-brands fa-github"></i>
            </a>
          </li>
          <li>
            <a
              class="contact__link"
              href="https://github.com/dream-ellie"
              target="_blank"
              title="my linkedin link"
            >
              <i class="fa-brands fa-linkedin"></i>
            </a>
          </li>
        </ul>
        <p class="description">donghe1472@gmail.com</p>
        <p class="description">si990819@gmail.com</p>
        <p class="description">hanse7260@gmail.com</p>

        <p class="description">moveg001115@gmail.com</p>
      </div>
    </footer>

     <script type="text/javascript" src="{% static 'js/arrow-sec.js' %}"></script>
   
   <script type="text/javascript" src="{% static 'js/arrowup.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/pic-filter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modal.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
     <script type="text/javascript" src="{% static 'js/pic-fav.js' %}"></script>
    <script>  
      const input = document.querySelector(".pic__search-bar");
      function onSubmit() {
        console.log(input.value);
      if(!input.value) {
        input.style.marginLeft = "10%";
      }

      else{
        console.log("dlskwl");
        input.classList.add("active");
      }
}

    document.querySelectorAll(".project").forEach(function(element) {
    console.log("Click event registered for element:", element);
    element.addEventListener("click", function() {
        console.log("Clicked!");
        window.location.href = element.getAttribute("href");
    });
});

    </script>
    {% endblock content %}

</html>

templates/products/search.html
{% extends "base.html" %} {% block page_title %} Home {% endblock page_title %}
{% block content %} {% endblock content %}