config/urls.py
from django.contrib import admin
from django.urls import path
from products import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("products.urls")),
    path("baskets/", include("baskets.urls")),
    path("users/", include("users.urls")),
    path("lists/", include("lists.urls")),
    path("conversations/", include("conversations.urls"))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kkma_chatbot-main/chatbot_test-main/restfulapiserver/urls.py
from django.urls import re_path as url
from django.urls import include
from addresses import views
from django.urls import path
from django.contrib import admin
from django.urls import re_path

urlpatterns = [
    path('addresses/', views.address_list),
    path('addresses/<int:pk>/', views.address),
    path('login/', views.login),
    path('app_login/', views.app_login),
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('chat_service/', views.chat_service),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:product_pk>", views.toggle_room, name="toggle_room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),]

users/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = "user"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("email_verify/", views.email_verify, name="verify"),
    path("verify/<str:key>", views.complete_verification,
         name="complete-verification"),
    # 비밀번호 초기화
    path('password_reset/', views.MyPasswordResetView.as_view(),
         name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path("password_verify/", views.password_verify, name="password-verify"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
import uuid
from django.conf import settings


class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = ("male", "Male")
        FEMALE = ("female", "Female")

    class UserKindChoices(models.TextChoices):
        CLIENT = ("client", "Client")  # 외주하는 사람들
        STUDENT = ("student", "Student")  # 수정 => 대학생들

    avatar = models.ImageField(
        blank=True,
    )
    password = models.CharField(
        max_length=200,
    )
    email = models.CharField(
        max_length=150,
    )
    birth = models.CharField(
        max_length=8,
    )
    nickname = models.CharField(
        max_length=100,
    )
    gender = models.CharField(
        max_length=6,
        choices=GenderChoices.choices,
    )
    phone_num = models.PositiveBigIntegerField(null=True, blank=True)
    user_kind = models.CharField(
        max_length=10,
        choices=UserKindChoices.choices,
    )
    location = models.CharField(
        max_length=100,
    )

    email_confirmed = models.BooleanField(default=False, verbose_name='이메일인증')
    email_secret = models.CharField(
        max_length=120, default="", blank=True, verbose_name='유저이름')

    def verify_email(self):
        if self.email_confirmed is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Daljak",
                strip_tags(html_message),
                "donghe1472@gmail.com",
                [self.email],
                html_message=html_message,
            )
        return


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 좋아요를 누른 사용자
    item_id = models.CharField(max_length=100)  # 좋아요한 항목의 ID (예: project1)
    # 좋아요 상태 (True: 좋아요, False: 좋아요 취소)
    is_liked = models.BooleanField(default=True)

users/forms.py
from django import forms
from . import models
import django.contrib.auth.forms as auth_forms
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(
                    "password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("username", forms.ValidationError(
                "User does not exist"))


class SignUpForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label="패스워드확인")

    class Meta:
        model = models.User
        fields = ("username","email", "password",  )
        
    widget = {
            "username": forms.TextInput(attrs={'placeholder': '이름을 입력해주세요'}),
            "password": forms.PasswordInput,
            "password1": forms.PasswordInput,
            "major": forms.TextInput(attrs={'placeholder': '학과을 입력해주세요'}),

        }

    def clean_email(self):
        email = self.cleaned_data.get("email")

        # if not email.endswith('@wku.ac.kr'):
        #     raise ValidationError(
        #         "오직 wku.ac.kr로만 가입가능합니다")

        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("이미 이메일을 가지고 있습니다")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다")
        else:
            return password

    def save(self,  *args, **kwargs):
        user = super().save(commit=False)
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        
        user.email = email

        user.username = username
        user.set_password(password)

        user.save()


class PasswordResetForm(auth_forms.PasswordResetForm):
    username = auth_forms.UsernameField(label="사용자ID")  # CharField 대신 사용

    # validation 절차:
    # 1. username에 대응하는 User 인스턴스의 존재성 확인
    # 2. username에 대응하는 email과 입력받은 email이 동일한지 확인

    def clean_username(self):
        data = self.cleaned_data['username']
        if not models.User.objects.filter(username=data).exists():
            raise ValidationError("해당 사용자ID가 존재하지 않습니다.")

        return data

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get("email")

        if username and email:
            if models.User.objects.get(username=username).email != email:
                raise ValidationError("사용자의 이메일 주소가 일치하지 않습니다")

    def get_users(self, email=''):
        active_users = models.User.objects.filter(**{
            'username__iexact': self.cleaned_data["username"],

        })
        return (
            u for u in active_users
            if u.has_usable_password()
        )

users/views.py
from django.views import View
from django.shortcuts import render
from django.views.generic import FormView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from . import forms
from . import models
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import auth
from django.contrib.auth.models import User  # User model 연결
from django.views.generic import TemplateView
# 오브젝트를 생성하는 뷰 (form 혹은 model과 연결되서 새로운 데이터를 넣을 때 CreateView - generic view를 사용)
from django.views.generic.edit import CreateView
# from django.contrib.auth.forms import UserCreationForm  >>  장고의 기본 회원가입 폼 (ID, PW만 확인한다 - 뒤에서 이메일 추가 커스터미아징 예정)
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView

# Create your views here.


class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                print("hello")
                login(request, user)
                return redirect(reverse("product:home"))
        return render(request, "users/login.html", {"form": form})


def log_out(request):
    logout(request)
    return redirect(reverse("product:home"))


class SignUpView(FormView):

    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("user:verify")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


class UserProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


def email_verify(request):

    return render(request, "users/email_verify.html")


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_confirmed = True
        user.email_secret = ""
        user.save()
        if user is not None:
            auth.login(request, user)
        # to do: add succes message
    except models.User.DoesNotExist:
        # to do: add error message
        pass
    return redirect(reverse("product:home"))


class UpdatePasswordView(PasswordChangeView):

    template_name = "users/update-password.html"


class MyPasswordResetView(PasswordResetView):
    success_url = reverse_lazy("user:password-verify")
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset.html'
    mail_title = "비밀번호 재설정"

    def form_valid(self, form):
        return super().form_valid(form)


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("core:project")
    template_name = 'users/password_reset_confirm.html'

    def form_valid(self, form):
        return super().form_valid(form)


def password_verify(request):

    return render(request, "users/password_reset_complete.html")

templates/users/email_verify.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="signup-page">
  {% load static %} {% include 'base.html' %}
  <div class="signup__form">
    <h1 class="login__title">Sign Up Daljak</h1>

    <form method="POST" action="{% url 'user:signup' %}">
      {% csrf_token %}
      <div class="signup__input">
        {{form.as_p}}
        <button class="login__btn signup__btn">
          이메일로 링크를 보냈습니다
        </button>
      </div>
    </form>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/login.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="login-page">
  <link rel="stylesheet" href="{% static 'css/users/login-content.css' %}" />

  <div class="login">
    <div class="login-content">
      <img
        class="login-content__img"
        src="{% static 'imgs/university.jpg' %}"
        alt=""
      />
      <div class="login-content__form">
        <h1 class="login__title">Login</h1>
        <form method="POST" action="{% url 'user:login'%}">
          {% csrf_token %} {{form.as_p}}

          <button class="login__btn" type="submit">로그인</button>
          <div class="login-content__signin">
            <a href="{% url 'user:signup'%}">회원가입</a>
            <a href="{% url 'user:password_reset' %}">비밀번호 찾기</a>
          </div>
        </form>
      </div>
    </div>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/password-find.html
<head>
    <link rel="stylesheet" href="../../static/css/components/status-bar.css" />
    <link rel="stylesheet" href="../../static/css/components/create-page.css" />
    <link rel="stylesheet" href="../../static/css/components/button.css" />
    <link rel="stylesheet" href="../../static/css/users/password-find.css" />
</head>

<body id="password-find-page">
    <div class="password-find">
        <div class="password-find-content__form">
            <h1 class="password-find__title">Find password</h1>
            <form method="POST">
                <input name="username" type="email" placeholder="이메일" />
                <button class="password-find__btn" type="submit">다음</button>
            </form>
        </div>
    </div>
</body>

<body id="password-find-page">
    <div class="password-find">
        <div class="password-find-content__form">
            <h1 class="password-find__title">Find password</h1>
            <form method="POST">
                {% csrf_token %} {{ form.as_p }}
                <input type="submit" value="Send me instructions!" />
            </form>
        </div>
    </div>
</body>

templates/users/password-go-email.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="signup-page">
  {% load static %} {% include 'base.html' %}
  <div class="signup__form">
    <h1 class="login__title">Sign Up Daljak</h1>

    <form method="POST" action="{% url 'user:signup' %}">
      {% csrf_token %}
      <div class="signup__input">
        {{form.as_p}}
        <button class="login__btn signup__btn">
          이메일로 링크를 보냈습니다
        </button>
      </div>
    </form>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/password_reset.html
{% autoescape off %} 안녕하세요 :) 다음 링크를 누르시면 계정의 비밀번호를 재설정 할 수 있는 화면으로 이동합니다. {{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %} 비밀번호 재설정을 요청하지 않았다면 이 이메일을 무시하셔도 됩니다. 에니악과 함께해주셔서 감사합니다. {% endautoescape %}

templates/users/password_reset_complete.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="signup-page">
  {% load static %} {% include 'base.html' %}
  <div class="signup__form">
    <h1 class="login__title">
      입력하신 이메일로<br />
      링크를 보냈습니다
    </h1>

    <form method="POST" action="{% url 'user:signup' %}">
      {% csrf_token %}
      <div class="signup__input">
        {{form.as_p}}
        <button class="login__btn signup__btn">확인</button>
      </div>
    </form>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/password_reset_confirm.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="login-page">
  <link rel="stylesheet" href="{% static 'css/users/login-content.css' %}" />

  <div class="login">
    <div class="login-content">
      <img
        class="login-content__img"
        src="{% static 'imgs/university.jpg' %}"
        alt=""
      />
      <div class="login-content__form">
        <h1 class="login__title">Login</h1>
        <form method="POST" action="{% url 'user:login'%}">
          {% csrf_token %} {{form.as_p}}

          <button class="login__btn" type="submit">바꾸기</button>
          <div class="login-content__signin">
            <a href="{% url 'user:signup'%}">회원가입</a>
            <a href="{% url 'user:password_reset' %}">비밀번호 찾기</a>
          </div>
        </form>
      </div>
    </div>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/password_reset_done.html
<body id="login-page">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/users/login-content.css' %}" /> {% include 'base.html' %}
    <div class="login">
        <div class="login-content">
            <img class="login-content__img" src="{% static 'img/login-img.jpg' %}" alt="" />
            <div class="login-content__form">
                <h1>Login Eniac</h1>
                <div>이메일로 폼이 발송되었습니다</div>
            </div>
        </div>
    </div>
    {% include 'partials/footer.html' %}
</body>

templates/users/password_reset_fail.html
<h1>존재하지 않는 메일입니다</h1>

templates/users/password_reset_form.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="login-page">
  <link rel="stylesheet" href="{% static 'css/users/login-content.css' %}" />

  <div class="login">
    <div class="login-content">
      <img
        class="login-content__img"
        src="{% static 'imgs/university.jpg' %}"
        alt=""
      />
      <div class="login-content__form">
        <h1 class="login__title">Find password</h1>
        <form method="POST">
          {% csrf_token %} {{form.as_p}}

          <button class="login__btn" type="submit">로그인</button>
          <div class="login-content__signin">
            <a href="{% url 'user:signup'%}">회원가입</a>
            <a href="{% url 'user:password_reset' %}">비밀번호 찾기</a>
          </div>
        </form>
      </div>
    </div>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/password_reset_verify.html
<body id="login-page">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/users/login-content.css' %}" /> {% include 'base.html' %}
    <div class="login">
        <div class="login-content">
            <img class="login-content__img" src="{% static 'img/login-img.jpg' %}" alt="" />
            <div class="login-content__form">
                <div>이메일을 확인해주세요</div>
            </div>
        </div>
    </div>
    {% include 'partials/footer.html' %}
</body>

templates/users/signup.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}

<head>
  <script
    src="https://kit.fontawesome.com/132c10257e.js"
    crossorigin="anonymous"
  ></script>
  <script
    type="module"
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
  ></script>
  <script
    nomodule
    src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
  ></script>
</head>
<body id="signup-page">
  {% load static %} {% include 'base.html' %}
  <div class="signup__form">
    <h1 class="login__title">Sign Up Daljak</h1>

    <form method="POST" action="{% url 'user:signup' %}">
      {% csrf_token %}
      <div class="signup__input">
        {{form.as_p}}
        <button class="login__btn signup__btn">다음</button>
      </div>
    </form>
  </div>
  <section id="contact" class="section">
    <h2 class="contact__email">donghe1472@gmail.com</h2>
    <div class="contact__links">
      <a href="https://github.com/dream-ellie" target="_blank">
        <i class="fab fa-github"></i>
      </a>
      <a href="#" target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </div>
    <p class="contact__rights">2023 prodouct</p>
  </section>
</body>

templates/users/user_detail.html
{% include "base.html" %} {% load static %} {% include 'partials/nav.html' %}
<div class="profile">
  <div class="profile__content">
    <div class="profile-left">
      <div class="profile__info">
        ◽ 이름: <span>{{user_obj.username}}</span>
      </div>
      <div class="profile__info">
        ◽ 이메일: <span>{{user_obj.email}}</span>
      </div>
    </div>
  </div>
</div>